#!/bin/bash
mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" -e "
CREATE DATABASE IF NOT EXISTS \`reconmap\` CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
CREATE USER IF NOT EXISTS '${MYSQL_RECONMAP_USER}'@'%' IDENTIFIED BY '${MYSQL_RECONMAP_PASSWORD}';
GRANT ALL ON \`reconmap\`.* TO '${MYSQL_RECONMAP_USER}'@'%';

CREATE DATABASE IF NOT EXISTS \`keycloak\` CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
CREATE USER IF NOT EXISTS '${MYSQL_KEYCLOAK_USER}'@'%' IDENTIFIED BY '${MYSQL_KEYCLOAK_PASSWORD}';
GRANT ALL ON \`keycloak\`.* TO '${MYSQL_KEYCLOAK_USER}'@'%';
"
