name: reconmap

volumes:
  redis_data:
  mysql_varlib:
  dataprotection-keys:
  rustfs_data:
  rustfs_logs:

services:
  redis:
    image: redis:8.6-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD} --save 20 1 --loglevel warning
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:4.2-alpine
    restart: unless-stopped
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  mysql:
    image: ghcr.io/reconmap/rest-api-db:latest
    build:
      context: .
      dockerfile: infra/docker/mysql/Dockerfile
    restart: unless-stopped
    volumes:
      - mysql_varlib:/var/lib/mysql
      - ./infra/docker/mysql/initdb:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_RECONMAP_USER: ${MYSQL_RECONMAP_USER}
      MYSQL_RECONMAP_PASSWORD: ${MYSQL_RECONMAP_PASSWORD}
      MYSQL_KEYCLOAK_USER: ${MYSQL_KEYCLOAK_USER}
      MYSQL_KEYCLOAK_PASSWORD: ${MYSQL_KEYCLOAK_PASSWORD}
    healthcheck:
      test: "mysql -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD mysql -e 'SELECT 1;'"
      interval: 5s
      timeout: 10s
      retries: 5

  keycloak:
    image: ghcr.io/reconmap/keycloak-custom:latest
    command: "start --hostname-strict=false --proxy-headers xforwarded --http-enabled true --import-realm"
    # See https://www.keycloak.org/server/all-config
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD}
      KC_DB: mysql
      KC_DB_URL_HOST: mysql
      KC_DB_DATABASE: keycloak
      KC_DB_USERNAME: ${MYSQL_KEYCLOAK_USER}
      KC_DB_PASSWORD: ${MYSQL_KEYCLOAK_PASSWORD}
      VAR_DASHBOARD_URL: "http://localhost:5500"
      VAR_ADMIN_CLIENT_SECRET: "${KEYCLOAK_ADMIN_CLIENT_SECRET}"
      VAR_RECONMAPD_CLIENT_SECRET: "${KEYCLOAK_RECONMAPD_CLIENT_SECRET}"
      VAR_API_CLIENT_SECRET: "${KEYCLOAK_API_CLIENT_SECRET}"
    restart: unless-stopped
    ports:
      - "8080:8080"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e 'GET /health/ready HTTP/1.1\r

            host: http://localhost\r

            Connection: close\r

            \r

            ' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;"
        ]
      interval: 30s
      timeout: 10s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy

  dashboard:
    profiles: ["app"]
    container_name: rmap-dashboard
    image: ghcr.io/reconmap/dashboard:latest
    restart: unless-stopped
    volumes:
      - ./config-ui.json:/usr/share/nginx/html/config.json:ro
    ports:
      - "5500:5500"
    depends_on:
      keycloak:
        condition: service_healthy

  ngapi:
    profiles: ["app"]
    image: ghcr.io/reconmap/ng-api:latest
    build:
      context: ./apps/api/src
      dockerfile: docker/Dockerfile
    volumes:
      - "./config-ngapi.json:/app/appsettings.json"
      - dataprotection-keys:/root/.aspnet/DataProtection-Keys
    ports:
      - "5510:5510"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5510
      - ConnectionStrings__MySqlConnection=server=mysql;port=3306;database=reconmap;user=${MYSQL_RECONMAP_USER};password=${MYSQL_RECONMAP_PASSWORD}
      - Redis__Password=${REDIS_PASSWORD}
      - Keycloak__ClientSecret=${KEYCLOAK_API_CLIENT_SECRET}
      - Storage__S3__SecretKey=${RUSTFS_SECRET_KEY}
      - Opa__ServerUrl=${OPA_SERVER_URL}
    depends_on:
      mysql:
        condition: service_healthy
      rustfs:
        condition: service_started

  agent:
    profiles: [ 'agent' ]
    image: ghcr.io/reconmap/agent:latest
    restart: unless-stopped
    ports:
      - "5520:5520"
    volumes:
      - "./config-agent.json:/root/.config/reconmap/config-reconmapd.json"
    command: /app/reconmapd run
    environment:
      RMAP_KEYCLOAK_DEBUG: "false"
      RMAP_KEYCLOAK_SKIP_TLS_VERIFY: "true"
      RMAP_KEYCLOAK_CLIENT_SECRET: "${KEYCLOAK_RECONMAPD_CLIENT_SECRET}"
      RMAP_REDIS_PASSWORD: "${REDIS_PASSWORD}"

  rustfs:
    image: rustfs/rustfs:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - rustfs_data:/data
      - rustfs_logs:/logs

  opa:
    image: openpolicyagent/opa:latest
    restart: unless-stopped
    ports:
      - "8181:8181"
    volumes:
      - ./policy:/policy
    command: ["run", "--server", "--addr", ":8181", "--log-format=json", "/policy"]
