apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: keycloak
  name: keycloak
  namespace: nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak
  template:
    metadata:
      labels:
        io.kompose.service: keycloak
    spec:
      containers:
        - args:
            - start
            - --hostname-strict=false
            - --proxy-headers
            - xforwarded
            - --http-enabled
            - "true"
            - --import-realm
          env:
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: admin
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: admin
            - name: KC_DB
              value: mysql
            - name: KC_DB_DATABASE
              value: keycloak
            - name: KC_DB_PASSWORD
              value: keycloaked
            - name: KC_DB_URL_HOST
              value: mysql
            - name: KC_DB_USERNAME
              value: keycloaker
            - name: VAR_ADMIN_CLIENT_SECRET
              value: r2TO5uRy0RlpB5TRI6GvvXtBKxUCaaz0
            - name: VAR_API_CLIENT_SECRET
              value: I0jppD5zSIXuBAql31zrXfe5OAa0nvyE
            - name: VAR_RECONMAPD_CLIENT_SECRET
              value: VH8HDKabxlTpnpPkEgLlTq2dEanedEGC
            - name: VAR_WEB_CLIENT_URL
              value: http://localhost:5500
          image: ghcr.io/reconmap/keycloak-custom:latest
          livenessProbe:
            exec:
              command:
                - "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;"
            failureThreshold: 10
            periodSeconds: 30
            timeoutSeconds: 10
          name: rmap-keycloak
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
