
interface AssetInterface {

	project_id: number | undefined;
	parent_id?: number;
	name: string | undefined;
	type: string | undefined;
	tags?: string;
}


/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const Asset : AssetInterface = {

	parent_id: undefined,

	project_id: undefined,
	name: undefined,
	type: undefined,
}

export default Asset;
