interface AttachmentInterface {
    id?: number;
    parentType: string | undefined;
    parentId: number | undefined;
    submitterUid: number | undefined;
    clientFileName: string | undefined;
    fileName: string | undefined;
    fileSize: number | undefined;
    fileMimetype?: string;
    fileHash: string | undefined;
}

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const Attachment: AttachmentInterface = {
    id: undefined,

    parentType: undefined,
    parentId: undefined,
    submitterUid: undefined,
    clientFileName: undefined,
    fileName: undefined,
    fileSize: undefined,
    fileHash: undefined,
};

export default Attachment;
