interface ClientInterface {
    id?: number;
    createdByUid?: number;
    kind: string | undefined;
    createdAt?: string;
    updatedAt?: string;
    name?: string;
    address?: string;
    url?: string;
    logo_attachment_id?: number;
    small_logo_attachment_id?: number;
}

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const Client: ClientInterface = {
    logo_attachment_id: undefined,
    small_logo_attachment_id: undefined,

    kind: undefined,
};

export default Client;
