interface CommandScheduleInterface {
    id?: number;
    createdByUid?: number;
    commandId?: number;
    argumentValues?: string;
    cronExpression?: string;
}

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const CommandSchedule: CommandScheduleInterface = {};

export default CommandSchedule;
