interface CommandUsageInterface {
    id?: number;
    commandId?: number;
    createdByUid?: number;
    name?: string;
    description?: string;
    executablePath?: string;
    arguments?: string;
    outputCapturingMode: string | undefined;
    outputFilename?: string;
    outputParser?: string;
}

export { CommandUsageInterface };

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const CommandUsage: CommandUsageInterface = {
    outputCapturingMode: "none",
};

export default CommandUsage;
