interface CustomFieldInterface {
    id?: number;
    parentType?: string;
    name?: string;
    label?: string;
    kind?: string;
    config?: string;
}

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const CustomField: CustomFieldInterface = {};

export default CustomField;
