interface DocumentInterface {
    userId?: number;
    visibility: string | undefined;
    parentId?: number;
    parentType?: string;
    content?: string;
    title?: string;
}

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const Document: DocumentInterface = {
    visibility: "private",
};

export default Document;
