
interface NotificationInterface {

	toUserId: number | undefined;
	title?: string;
	content: string | undefined;
}


/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const Notification : NotificationInterface = {


	toUserId: undefined,
	content: undefined,
}

export default Notification;
