
interface TargetInterface {

	project_id: number | undefined;
	parent_id?: number;
	name: string | undefined;
	kind: string | undefined;
	tags?: string;
}


/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const Target : TargetInterface = {

	parent_id: undefined,

	project_id: undefined,
	name: undefined,
	kind: undefined,
}

export default Target;
