interface TaskInterface {
    id?: number;
    projectId?: number;
    createdByUid?: number;
    assignedToUid?: number;
    createdAt?: string;
    updatedAt?: string;
    priority: string | undefined;
    summary: string | undefined;
    description?: string;
    status: string | undefined;
    durationEstimate?: number;
    dueDate?: string;
    command?: string;
    command_parser?: string;
}

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const Task: TaskInterface = {
    priority: "medium",
    summary: "",
    description: "",
    status: "todo",
    durationEstimate: undefined,
    dueDate: undefined,
};

export default Task;
