interface UserInterface {
    id?: number;
    subjectId?: string;
    role?: string;
    shortBio?: string;
    preferences: any | undefined;

    // Identity fields are owned by Keycloak and returned merged by the API.
    username: string | undefined;
    email: string | undefined;
    firstName: string | undefined;
    lastName: string | undefined;
    fullName?: string;
    active?: boolean;
    createdAt?: string;
    updatedAt?: string;
    lastLoginAt?: string;
    locale?: string;
    timezone: string | undefined;
    mfaEnabled?: boolean;
}

export { UserInterface };

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const User: UserInterface = {
    active: true,
    mfaEnabled: false,
    fullName: "",
    role: undefined,

    firstName: undefined,
    lastName: undefined,
    username: undefined,
    email: undefined,
    locale: undefined,
    timezone: undefined,
    preferences: undefined,
};

export default User;
