interface UserInterface {
    id?: number;
    createdAt?: string;
    updatedAt?: string;
    lastLoginAt?: string;
    subject_id?: string;
    active?: boolean;
    mfaEnabled: boolean | undefined;
    firstName: string | undefined;
    lastName: string | undefined;
    fullName?: string;
    short_bio?: string;
    username: string | undefined;
    email: string | undefined;
    timezone: string | undefined;
    preferences: any | undefined;
    role?: string;
}

export { UserInterface };

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const User: UserInterface = {
    active: true,
    mfaEnabled: false,
    fullName: "",
    role: undefined,

    firstName: undefined,
    lastName: undefined,
    username: undefined,
    email: undefined,
    timezone: undefined,
    preferences: undefined,
};

export default User;
