interface VaultInterface {
    id?: number;
    createdAt?: string;
    updatedAt?: string;
    owner_uid?: number;
    project_id?: number;
    type: string | undefined;
    name?: string;
    value?: string;
    url?: string;
    expiration_date?: string;
    note?: string;
}

/**
 * Autogenerated file, do not edit manually. @see https://github.com/reconmap/model-definitions
 */
const Vault: VaultInterface = {
    id: undefined,
    createdAt: undefined,
    updatedAt: undefined,
    owner_uid: undefined,
    project_id: undefined,
    type: "password",
    name: undefined,
    value: undefined,
    url: undefined,
    expiration_date: undefined,
    note: undefined,
};

export default Vault;
