global:
  namespace: nonprod

mysql:
  enabled: true
  image:
    repository: ghcr.io/reconmap/rest-api-db
    tag: latest
    pullPolicy: IfNotPresent
  rootPassword: reconmuppet
  database: reconmap
  user: reconmapper
  password: reconmapped
  keycloakUser: keycloaker
  keycloakPassword: keycloaked
  persistence:
    size: 100Mi

redis:
  enabled: true
  image:
    repository: redis
    tag: 8.6-alpine
    pullPolicy: IfNotPresent
  password: REconDIS
  persistence:
    size: 100Mi

rabbitmq:
  enabled: true
  image:
    repository: rabbitmq
    tag: 4.2-alpine
    pullPolicy: IfNotPresent
  defaultUser: guest
  defaultPass: guest

keycloak:
  enabled: true
  image:
    repository: ghcr.io/reconmap/keycloak-custom
    tag: latest
    pullPolicy: IfNotPresent
  bootstrapAdminUser: admin
  bootstrapAdminPassword: admin
  clientSecrets:
    admin: r2TO5uRy0RlpB5TRI6GvvXtBKxUCaaz0
    api: I0jppD5zSIXuBAql31zrXfe5OAa0nvyE
    agent: VH8HDKabxlTpnpPkEgLlTq2dEanedEGC
  webClientUrl: http://localhost:5500

api:
  enabled: true
  image:
    repository: ghcr.io/reconmap/ng-api
    tag: latest
    pullPolicy: IfNotPresent
  environment: Production
  urls: http://0.0.0.0:5510
  persistence:
    size: 100Mi

dashboard:
  enabled: true
  image:
    repository: ghcr.io/reconmap/web-client
    tag: latest
    pullPolicy: IfNotPresent
  apiUrl: http://localhost:5510/api
  notificationsUrl: ws://localhost:5510/api
  service:
    type: LoadBalancer
    port: 5500
