{{- if .Values.api.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "reconmap.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  name: ngapi
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "reconmap.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "reconmap.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.api.environment | quote }}
            - name: ASPNETCORE_URLS
              value: {{ .Values.api.urls | quote }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          name: ngapi
          ports:
            - containerPort: 5510
              protocol: TCP
          volumeMounts:
            - mountPath: /app/appsettings.json
              name: ngapi-config
              subPath: appsettings.json
            - mountPath: /root/.aspnet/DataProtection-Keys
              name: ngapi-storage
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: config-ngapi.json
                path: appsettings.json
            name: ngapi-configmap
          name: ngapi-config
        - name: ngapi-storage
          persistentVolumeClaim:
            claimName: ngapi-pvc
{{- end }}
