{{- if .Values.keycloak.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "reconmap.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
  name: keycloak
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "reconmap.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: keycloak
  template:
    metadata:
      labels:
        {{- include "reconmap.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: keycloak
    spec:
      containers:
        - args:
            - start
            - --hostname-strict=false
            - --proxy-headers
            - xforwarded
            - --http-enabled
            - "true"
            - --import-realm
          env:
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: {{ .Values.keycloak.bootstrapAdminPassword | quote }}
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: {{ .Values.keycloak.bootstrapAdminUser | quote }}
            - name: KC_DB
              value: mysql
            - name: KC_DB_DATABASE
              value: {{ .Values.mysql.database | quote }}
            - name: KC_DB_PASSWORD
              value: {{ .Values.mysql.keycloakPassword | quote }}
            - name: KC_DB_URL_HOST
              value: mysql
            - name: KC_DB_USERNAME
              value: {{ .Values.mysql.keycloakUser | quote }}
            - name: VAR_ADMIN_CLIENT_SECRET
              value: {{ .Values.keycloak.clientSecrets.admin | quote }}
            - name: VAR_API_CLIENT_SECRET
              value: {{ .Values.keycloak.clientSecrets.api | quote }}
            - name: VAR_RECONMAPD_CLIENT_SECRET
              value: {{ .Values.keycloak.clientSecrets.agent | quote }}
            - name: VAR_WEB_CLIENT_URL
              value: {{ .Values.keycloak.webClientUrl | quote }}
          image: "{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}"
          imagePullPolicy: {{ .Values.keycloak.image.pullPolicy }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;"
            failureThreshold: 10
            periodSeconds: 30
            timeoutSeconds: 10
          name: rmap-keycloak
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
{{- end }}
