{{- if .Values.mysql.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "reconmap.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
  name: mysql
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "reconmap.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "reconmap.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_KEYCLOAK_PASSWORD
              value: {{ .Values.mysql.keycloakPassword | quote }}
            - name: MYSQL_KEYCLOAK_USER
              value: {{ .Values.mysql.keycloakUser | quote }}
            - name: MYSQL_RECONMAP_PASSWORD
              value: {{ .Values.mysql.password | quote }}
            - name: MYSQL_RECONMAP_USER
              value: {{ .Values.mysql.user | quote }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.rootPassword | quote }}
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - mysql -h 127.0.0.1 -u root --password=$MYSQL_ROOT_PASSWORD mysql -e 'SELECT 1;'
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 10
          name: rmap-mysql
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
      restartPolicy: Always
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
{{- end }}
