{{- if .Values.mysql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "reconmap.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
  name: mysql
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    {{- include "reconmap.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
{{- end }}
