{{- if .Values.rabbitmq.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "reconmap.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
  name: rabbitmq
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "reconmap.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rabbitmq
  template:
    metadata:
      labels:
        {{- include "reconmap.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: rabbitmq
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ .Values.rabbitmq.defaultPass | quote }}
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.rabbitmq.defaultUser | quote }}
          image: "{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}"
          imagePullPolicy: {{ .Values.rabbitmq.image.pullPolicy }}
          name: rmap-rabbitmq
          ports:
            - containerPort: 5672
              protocol: TCP
      restartPolicy: Always
{{- end }}
