{{- if .Values.redis.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "reconmap.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  name: redis
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "reconmap.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "reconmap.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - args:
            - redis-server
            - --requirepass
            - {{ .Values.redis.password | quote }}
            - --save
            - "20"
            - "1"
            - --loglevel
            - warning
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          name: rmap-redis
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: redis-storage
      restartPolicy: Always
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
{{- end }}
