{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "reconmap.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  name: redis-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size | default "100Mi" }}
{{- end }}
