apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: mysql
  name: mysql
  namespace: nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_KEYCLOAK_PASSWORD
              value: keycloaked
            - name: MYSQL_KEYCLOAK_USER
              value: keycloaker
            - name: MYSQL_RECONMAP_PASSWORD
              value: reconmapped
            - name: MYSQL_RECONMAP_USER
              value: reconmapper
            - name: MYSQL_ROOT_PASSWORD
              value: reconmuppet
          image: ghcr.io/reconmap/rest-api-db:latest
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - mysql -h 127.0.0.1 -u root --password=$MYSQL_ROOT_PASSWORD mysql -e 'SELECT 1;'
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 10
          name: mysql
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
      restartPolicy: Always
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
