apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: mysql
  name: mysql-pvc
  namespace: nonprod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
