apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ngapi
  name: ngapi
  namespace: nonprod
spec:
  ports:
    - name: "5253"
      port: 5253
      targetPort: 5253
  selector:
    app.kubernetes.io/name: ngapi
