apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ngapi
  name: ngapi
  namespace: nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ngapi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ngapi
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:5510
          image: ghcr.io/reconmap/ng-api:latest
          name: rmap-ngapi
          ports:
            - containerPort: 5510
              protocol: TCP
          volumeMounts:
            - mountPath: /app/appsettings.json
              name: ngapi-config
              subPath: appsettings.json
            - mountPath: /root/.aspnet/DataProtection-Keys
              name: ngapi-storage
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: config-ngapi.json
                path: appsettings.json
            name: ngapi-configmap
          name: ngapi-config
        - name: ngapi-storage
          persistentVolumeClaim:
            claimName: ngapi-pvc
