apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: ngapi
  name: ngapi-pvc
  namespace: nonprod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
