apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: postgres
  name: postgres
  namespace: nonprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_KEYCLOAK_PASSWORD
              value: keycloaked
            - name: POSTGRES_KEYCLOAK_USER
              value: keycloaker
            - name: POSTGRES_RECONMAP_PASSWORD
              value: reconmapped
            - name: POSTGRES_RECONMAP_USER
              value: reconmapper
            - name: POSTGRES_PASSWORD
              value: reconmuppet
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: postgres
          image: postgres:17-alpine
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U postgres
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 10
          name: postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
            - mountPath: /docker-entrypoint-initdb.d
              name: postgres-init-scripts
      restartPolicy: Always
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: postgres-init-scripts
          configMap:
            name: postgres-init-configmap
            items:
              - key: 00-databases.sh
                path: 00-databases.sh
              - key: 01-schema.sql
                path: sql/01-schema.sql
              - key: 02-default-data.sql
                path: sql/02-default-data.sql
