apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: rabbitmq
  name: rabbitmq
  namespace: nonprod
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
  selector:
    app.kubernetes.io/name: rabbitmq
