include:
  - path: ../../../compose.yaml

services:
  ngapi:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - "./appsettings.Production.json:/App/appsettings.Production.json"
      - "./appsettings.json:/App/appsettings.json"
