volumes:
  redis_data:
  mysql_varlib:
  dataprotection-keys:
  rustfs_data:
  rustfs_logs:

services:
  redis:
    extends:
      file: ../../compose.yaml
      service: redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --save 20 1 --loglevel warning

  rabbitmq:
    extends:
      file: ../../compose.yaml
      service: rabbitmq
    image: rabbitmq:4.2-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  mysql:
    extends:
      file: ../../compose.yaml
      service: mysql
    build:
      context: ../../
      dockerfile: infra/docker/mysql/Dockerfile
    healthcheck:
      retries: 3

  keycloak:
    extends:
      file: ../../compose.yaml
      service: keycloak
    command: "start --hostname-strict false --proxy-headers xforwarded --http-enabled true --import-realm  --hostname-debug=true"
    environment:
      KC_LOG_LEVEL: debug

  rustfs:
    extends:
      file: ../../compose.yaml
      service: rustfs
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - RUSTFS_ACCESS_KEY=${RUSTFS_ACCESS_KEY}
      - RUSTFS_SECRET_KEY=${RUSTFS_SECRET_KEY}
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001

  web-client:
    extends:
      file: ../../compose.yaml
      service: web-client
    profiles:
      - testing

  ngapi:
    extends:
      file: ../../compose.yaml
      service: ngapi
    build:
      context: ./src
      dockerfile: docker/Dockerfile
    volumes:
      - "./src/appsettings.Production.json:/App/appsettings.Production.json"
      - "./src/appsettings.json:/App/appsettings.json"
    profiles:
      - testing
