include:
  - path: ../../compose.yaml

services:
  redis:
    command: redis-server --requirepass REconDIS --save 20 1 --loglevel warning

  rabbitmq:
    image: rabbitmq:4.2-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  mysql:
    build:
      context: ../../
      dockerfile: infra/docker/mysql/Dockerfile
    healthcheck:
      retries: 3

  keycloak:
    command: "start --hostname-strict false --proxy-headers xforwarded --http-enabled true --import-realm  --hostname-debug=true"
    environment:
      KC_LOG_LEVEL: debug

  rustfs:
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001

  web-client:
    profiles:
      - testing

  ngapi:
    build:
      context: ./src
      dockerfile: docker/Dockerfile
    volumes:
      - "./src/appsettings.Production.json:/App/appsettings.Production.json"
      - "./src/appsettings.json:/App/appsettings.json"
    profiles:
      - testing
