name: API

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apps/api

    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PAT }}

      - name: Run containers
        run: docker compose -p rest-api up -d

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal

      - name: Push NGAPI image
        run: make build push
        working-directory: app

