name: Docker MySQL image

on:
  push:
    branches:
      - main
    paths:
      - 'infra/docker/mysql/**'
      - '.github/workflows/docker-mysql-build-push.yml'

jobs:
  default:
    name: Build and push
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: infra/docker/mysql    

    steps:
      - uses: actions/checkout@v6

      - name: Login to container registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u "${{ secrets.CR_USERNAME }}" --password-stdin

      - name: Build image
        run: make image-build

      - name: Push image
        run: make image-push
